apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.app}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: 80
    targetPort: 9020
  selector:
    app: {{.Values.app}}
